### PR TITLE
Add cocoapods spec

### PR DESCRIPTION
**Pull request by aroldan**
Hey foursquare people!

I love the lightweight design of FSNetworking and we're looking to use it on a new iOS project at HubSpot. We use CocoaPods for dependency management -- could you add this podspec to your repo so people can pull it in with CocoaPods instead of manually inserting the files?

(Right now, it links to my fork of the repo, but once the Podspec is in yours, I imagine we'd want to move it over.)

### CODE REVIEW

**Comment by mickeyreiss** [comment]
+1

**Comment by gwk** [comment]
I only just looked at this now - sorry for the delay. Two minor points:
• The license is Apache 2, not MIT.
• I (George King, former FS engineer) am the original author; Bryan is the current maintainer.
I would appreciate these corrections, and agree that it should get merged into the official repo.
Thanks!

**Comment by mickeyreiss** [comment]
@gwk I take it this library isn't maintained anymore. What does foursquare use for the networking layer these days?

**Comment by gwk** [comment]
@mickeyreiss I know longer work at Foursquare, so I am not in a position to actively manage the official repo. I have not been doing much iOS work these days, and with the advent of NSURLSession in iOS 7 I am not sure if I would use it in a new project (I would have to assess the benefits of NSURLSession, and would also take another hard look at AFNetworking, which has adopted it).

@itsbonczek perhaps you could comment on the Foursquare team's current usage and interest in this project?

**Comment by bryanbonczek** [comment]
Hi everyone. Sorry for the delay in following up. It's been a busy summer at Foursquare HQ.

We still use FSN in the production Foursquare app and will for the near future. George makes a great point about NSURLSession and it's something we're definitely evaluating internally. We've been giving AF an honest evaluation since that's where most of the iOS community focuses their attention. We're certainly torn over the decision because since I do believe FSN is a fantastic library and has served us well for quite awhile now. But even if we upgraded FSN to use NSURLSession, it's still unclear to me as to what value FSN can provide over AF. So the decision comes down to whether we think FSN has a clear value proposition over AF, or if it would be better for the iOS community in the long run if our team of talented developers focused on making something AF as best as possible. It's still something we're wrestling with, but I would expect no major updates to FSN in the near term.

We're certainly open to thoughts and feedback from FSN users, so please drop me a note if you feel strongly either way :)

**Comment by ghost** [comment]
AFNetworking is a bit of a baby toy once you start trying to do anything serious with it. That wouldn't matter all that much if it didn't go out of its way to prevent you from getting your work done in as many ways as humanly possible just because somebody decided you'd never need to do anything their app doesn't. I'd prefer a lighter weight library that didn't pretend to be the end-all-be-all networking toolkit to a bloated loaf of mandatory subclassing where the parent classes override all of your overrides behind your back.

**Comment by aroldan** [comment]
We ultimately decided to go with AFNetworking and have been pretty happy with it. @oncomeme I think the new 2.x version makes customizing it a lot friendlier..sorry you've been having what sounds like a pretty bad time.

**Pull request closed without merging**
